### ISSUE TITLE
Filter by patient 

### ISSUE THREAD

**Issue by sidgan** [mauro-nievoff/MultiCaRe_Dataset#2]
Hi, 

I want to filter data for a single patient but with all the times the patient has visited the doctor, (or at least more than one time). Is that the same as one case id? or does one case id have information for only one visit of a single patient?

**Comment by mauro-nievoff** [comment]
Hi @sidgan, each case id refers to a different patient. Clinical cases are not split into different visits.

**Comment by sidgan** [comment]
Okay, so if I want all the cases for a single patient, how do I do that?

**Comment by mauro-nievoff** [comment]
In theory, multiple cases could refer to the same person (i.e. if the same patient is included in different case report articles at different moments of their life). But this situation is exceptional, and there is no way to identify it in this dataset (apart from manually checking clinical cases in order to identify coincidences in patient journeys).
